"""
Habit Dashboard

Generates a dashboard summarizing all habits.
"""

from gamification.utils import (
    load_config,
    absolute_path,
    read_markdown,
)

config = load_config()


def generate_dashboard():

    habits_folder = absolute_path(
        config["habits_folder"]
    )

    dashboard_path = absolute_path(
        config["habits_dashboard"]
    )

    habits = []

    total_habits = 0
    total_sessions = 0
    total_xp = 0
    active_today = 0

    for habit_file in habits_folder.rglob("*.md"):

        try:

            habit, body, keymap = read_markdown(habit_file)

            if habit.get("type", "").lower() != "habit":
                continue

            title = habit.get("title", habit_file.stem)
            unit = habit.get("unit", "")

            value = float(habit.get("value", 0))
            total_value = float(habit.get("totalvalue", 0))
            xp_per_unit = float(habit.get("xpperunit", 0))

            sessions = int(habit.get("timescompleted", 0))

            current = int(habit.get("currentstreak", 0))
            longest = int(habit.get("longeststreak", 0))

            xp = round(total_value * xp_per_unit, 2)

            if value > 0:
                active_today += 1

            total_habits += 1
            total_sessions += sessions
            total_xp += xp

            habits.append(
                {
                    "title": title,
                    "unit": unit,
                    "total": total_value,
                    "sessions": sessions,
                    "current": current,
                    "longest": longest,
                    "xp": xp,
                }
            )

        except Exception as e:
            print(f"Skipped {habit_file.name}: {e}")

    habits.sort(
        key=lambda h: h["xp"],
        reverse=True,
    )

    dashboard = """# 🏃 Habits Dashboard

> 🤖 Automatically generated by the Obsidian Gamification Engine.

---

# 📊 Summary

| Stat | Value |
|------|------:|
"""

    dashboard += f"| Total Habits | {total_habits} |\n"
    dashboard += f"| Active Today | {active_today} |\n"
    dashboard += f"| Total Sessions | {total_sessions} |\n"
    dashboard += f"| Total XP Earned | {total_xp:.2f} |\n"

    dashboard += """

---

# 🔥 Habit Streaks

| Habit | Current | Best |
|------|------:|------:|
"""

    for habit in habits:

        dashboard += (
            f"| {habit['title']} | "
            f"{habit['current']} | "
            f"{habit['longest']} |\n"
        )

    dashboard += """

---

# 📈 Habit Statistics

| Habit | Total | Unit | Sessions | XP |
|------|------:|------|------:|------:|
"""

    for habit in habits:

        dashboard += (
            f"| {habit['title']} | "
            f"{habit['total']:.2f} | "
            f"{habit['unit']} | "
            f"{habit['sessions']} | "
            f"{habit['xp']:.2f} |\n"
        )

    if habits:

        best = habits[0]

        dashboard += f"""

---

# 🥇 Top Habit

**{best['title']}**

- XP Earned : **{best['xp']:.2f}**
- Current Streak : **{best['current']}**
- Longest Streak : **{best['longest']}**
- Total : **{best['total']:.2f} {best['unit']}**
"""

    dashboard_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    dashboard_path.write_text(
        dashboard,
        encoding="utf-8",
    )

    print("Habit Dashboard Updated")